#!/usr/bin/bash

[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1

source "$(dirname ${0})"/buildit.conf || exit 1

# Build

# If there's no Makefile, then do a refresh
if [ ! -f "${BUILDIT_workarea_path}"/buildit/Makefile ]; then
    "$(dirname ${0})"/refresh
fi

# make && make install
make -C "${BUILDIT_workarea_path}"/buildit install
