#!/usr/bin/bash

[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1

source "$(dirname ${0})"/buildit.conf || exit 1

# Clean

if [ -d "${BUILDIT_workarea_path}"/buildit ]; then
    # Delete old build objects
    make -C "${BUILDIT_workarea_path}"/buildit clean
fi
