#!/usr/bin/bash

[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1

source "$(dirname ${0})"/buildit.conf || exit 1

# Debug

# Build and run through the GNU debugger
"$(dirname ${0})"/build || exit 1
gdb -ex run --args "${BUILDIT_workarea_path}"/bin/${BUILDIT_project} "$@"
