#!/usr/bin/bash

[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1

source "$(dirname ${0})"/buildit.conf || exit 1

# Refresh

# Start by wiping the working area
"$(dirname ${0})"/wipe || exit 1

# Recreate the working area and go to it
mkdir -p "${BUILDIT_workarea_path}"/buildit || exit 1
cd "${BUILDIT_workarea_path}"/buildit || exit 1

# Startup GNU Autotools
autoreconf --install "${BUILDIT_project_path}" || exit 1

# Configure the project
"${BUILDIT_project_path}"/configure --enable-silent-rules --prefix="${BUILDIT_workarea_path}"
