#!/usr/bin/bash

[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1

[ -f buildit.conf.EXAMPLE ] && echo "ERROR: Do not run from the buildit directory." && exit 1

ln -s "$(dirname ${0})"/build || exit 1
ln -s "$(dirname ${0})"/clean || exit 1
ln -s "$(dirname ${0})"/debug || exit 1
ln -s "$(dirname ${0})"/refresh || exit 1
ln -s "$(dirname ${0})"/run || exit 1
ln -s "$(dirname ${0})"/wipe || exit 1

cp "$(dirname ${0})"/buildit.conf.EXAMPLE buildit.conf || exit 1

echo "Done."
echo "Change the project name in \"buildit.conf\" before using."
